### ISSUE TITLE
Error when connecting Label Studio

### ISSUE THREAD

**Issue by d4rkm0nkey** [tim-smart/label-studio-spacy#2]
I get this error when connecting the URL to Label Studio.
```
[ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1677507464 job returns exception: 
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
```
This is the config.cfg I have in the folder
```
[paths]
train = null
dev = null
vectors = "de_core_news_lg"
[system]
gpu_allocator = null

[nlp]
lang = "de"
pipeline = ["tok2vec","ner","parser"]
batch_size = 1000

[components]

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v2"
width = ${components.tok2vec.model.encode.width}
attrs = ["NORM", "PREFIX", "SUFFIX", "SHAPE"]
rows = [5000, 1000, 2500, 2500]
include_static_vectors = true

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 256
depth = 8
window_size = 1
maxout_pieces = 3

[components.parser]
factory = "parser"

[components.parser.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "parser"
extra_state_tokens = false
hidden_width = 128
maxout_pieces = 3
use_upper = true
nO = null

[components.parser.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}

[components.ner]
factory = "ner"

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}

[corpora]

[corpora.train]
@readers = "spacy.Corpus.v1"
path = ${paths.train}
max_length = 0

[corpora.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.dev}
max_length = 0

[training]
dev_corpus = "corpora.dev"
train_corpus = "corpora.train"

[training.optimizer]
@optimizers = "Adam.v1"

[training.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2

[training.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001

[initialize]
vectors = ${paths.vectors}
```

**Comment by d4rkm0nkey** [comment]
I tried out a bit and sometimes I also get this error:
```
[2023-02-27 15:35:11,447] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/api.py", line 93, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 711, in train
    job_result = cls.train_script_wrapper(
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 667, in train_script_wrapper
    train_output = m.model.fit(data_stream, workdir, **train_kwargs)
  File "/home/user/Documents/projects/spacy/label-studio-spacy/german/model.py", line 187, in fit
    annotations_to_docbin(
  File "/home/user/Documents/projects/spacy/label-studio-spacy/german/model.py", line 261, in annotations_to_docbin
    if not item['data']['text']:
KeyError: 'text'

Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/api.py", line 93, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 711, in train
    job_result = cls.train_script_wrapper(
  File "/home/user/miniconda3/lib/python3.10/site-packages/label_studio_ml/model.py", line 667, in train_script_wrapper
    train_output = m.model.fit(data_stream, workdir, **train_kwargs)
  File "/home/user/Documents/projects/spacy/label-studio-spacy/german/model.py", line 187, in fit
    annotations_to_docbin(
  File "/home/user/Documents/projects/spacy/label-studio-spacy/german/model.py", line 261, in annotations_to_docbin
    if not item['data']['text']:
KeyError: 'text'
```
