### ISSUE TITLE
Assertion error on training `assert isinstance(result, dict)`

### ISSUE THREAD

**Issue by shiva-kumarj** [tim-smart/label-studio-spacy#4]
The data is prepared in the same format as shown in your youtube video for spacy ml backend [Using spaCy as a ML backend for Label Studio
](https://www.youtube.com/watch?v=F19NT-21uT4)

All the setup steps were successful. 

On starting training, the below error pops up.

```
PS D:\My-Projects\label-studio-spacy> label-studio-ml start .\review_classification_backend\

C:\Users\blahb\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

C:\Users\blahb\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(
 * Serving Flask app "label_studio_ml.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

[2023-07-13 09:43:18,595] [WARNING] [werkzeug::_log::225]  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2023-07-13 09:43:18,595] [INFO] [werkzeug::_log::225]  * Running on http://192.168.0.7:9090/ (Press CTRL+C to quit)
[2023-07-13 09:44:06,541] [INFO] [werkzeug::_log::225] 192.168.0.7 - - [13/Jul/2023 09:44:06] "GET /health HTTP/1.1" 200 -
[2023-07-13 09:44:06,557] [ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1689188320 job returns exception:

Traceback (most recent call last):
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
```
And below is a sample of my data

```
{
    "data": {
      "text": "their firs kind of stink but you dont come here for the fries."
    }
  },
  { "data": { "text": "its an okay establishment." } }

```

How can I debug this?

**Comment by gabrielnogueiracsc** [comment]
i'm getting the same error. Do you get a way to fix that?
